/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.CitaDAOImplm;
import interfaces.CitaDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import modelo.Cita;
import sistemaconsultorionutri.Dashboard;
import static sistemaconsultorionutri.Dashboard.showView;

/**
 *
 * @author Yair
 */
public class ReagendarCita extends javax.swing.JPanel {

    /**
     * Creates new form Citas
     */
    public ReagendarCita() {
        initComponents();
        rellenarFechas();
    }

    private void rellenarFechas() {
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy"); // Agregamos "EEEE" para el día de la semana
        DefaultComboBoxModel<String> fechaModel = new DefaultComboBoxModel<>();

        for (int i = 0; i < 34; i++) {
            fechaModel.addElement(currentDate.format(formatter));
            currentDate = currentDate.plusDays(1);
        }

        boxFecha.setModel(fechaModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNoCita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxFecha = new javax.swing.JComboBox<>();
        btnReagendar = new javax.swing.JButton();
        btnReagendar1 = new javax.swing.JButton();
        boxHora = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(788, 496));
        setPreferredSize(new java.awt.Dimension(988, 588));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Reagendar cita");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("No. Cita:");

        txtNoCita.setEditable(false);
        txtNoCita.setBackground(new java.awt.Color(255, 255, 255));
        txtNoCita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNoCita.setForeground(new java.awt.Color(102, 102, 102));
        txtNoCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtNoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoCitaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Paciente:");

        txtPaciente.setEditable(false);
        txtPaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPaciente.setForeground(new java.awt.Color(102, 102, 102));
        txtPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Fecha y hora:");

        boxFecha.setBackground(new java.awt.Color(255, 255, 255));
        boxFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day Hour" }));
        boxFecha.setBorder(null);
        boxFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFechaActionPerformed(evt);
            }
        });

        btnReagendar.setBackground(new java.awt.Color(0, 102, 102));
        btnReagendar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnReagendar.setForeground(new java.awt.Color(255, 255, 255));
        btnReagendar.setText("Cancelar");
        btnReagendar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 15, new java.awt.Color(0, 0, 0)));
        btnReagendar.setBorderPainted(false);
        btnReagendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReagendar.setFocusPainted(false);
        btnReagendar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReagendar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReagendar.setIconTextGap(10);
        btnReagendar.setSelected(true);
        btnReagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagendarActionPerformed(evt);
            }
        });

        btnReagendar1.setBackground(new java.awt.Color(0, 102, 102));
        btnReagendar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnReagendar1.setForeground(new java.awt.Color(255, 255, 255));
        btnReagendar1.setText("Reagendar");
        btnReagendar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 15, new java.awt.Color(0, 0, 0)));
        btnReagendar1.setBorderPainted(false);
        btnReagendar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReagendar1.setFocusPainted(false);
        btnReagendar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReagendar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReagendar1.setIconTextGap(10);
        btnReagendar1.setSelected(true);
        btnReagendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagendar1ActionPerformed(evt);
            }
        });

        boxHora.setBackground(new java.awt.Color(255, 255, 255));
        boxHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        boxHora.setForeground(new java.awt.Color(102, 102, 102));
        boxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00 A.M.", "08:00 A.M.", "09:00 A.M.", "10:00 A.M.", "11:00 A.M.", "12:00 P.M.", "01:00 P.M.", "02:00 P.M.", "03:00 P.M.", "04:00 P.M.", "05:00 P.M.", "06:00 P.M." }));
        boxHora.setBorder(null);
        boxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoCita)
                    .addComponent(txtPaciente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(btnReagendar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReagendar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(boxFecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReagendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/nutritionist-agenda.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoCitaActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btnReagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagendarActionPerformed
        vistas.Citas citas = new Citas();
        showView(citas);
    }//GEN-LAST:event_btnReagendarActionPerformed

    private void btnReagendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagendar1ActionPerformed
        String fechaStr = String.valueOf(boxFecha.getSelectedItem());
        String hora = String.valueOf(boxHora.getSelectedItem());
        String estado = "Pendiente";
        String idCita = txtNoCita.getText();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy");
        LocalDate localDate = LocalDate.parse(fechaStr, formatter);

        // Convert LocalDate to java.sql.Date
        java.sql.Date sqlDate = java.sql.Date.valueOf(localDate);

        Cita cita = new Cita();
        cita.setEstado(estado);
        cita.setFecha(sqlDate); // Aquí estableces el objeto java.sql.Date
        cita.setHora(hora);
        cita.setCitaId(Integer.parseInt(idCita));

        CitaDAO citaDAO = new CitaDAOImplm();
        try {
            citaDAO.actualizar(cita);
            Dashboard.mostrarMensajeAviso("La cita ha sido reagendada con exito");

            vistas.Citas citas = new Citas();
            showView(citas);
        } catch (Exception ex) {
            Logger.getLogger(NuevaCita.class.getName()).log(Level.SEVERE, null, ex);
            Dashboard.mostrarMensajeError("No se pudo realizar la operación");
        }


    }//GEN-LAST:event_btnReagendar1ActionPerformed

    private void boxFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFechaActionPerformed

    private void boxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxHoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFecha;
    private javax.swing.JComboBox<String> boxHora;
    private javax.swing.JButton btnReagendar;
    private javax.swing.JButton btnReagendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTextField txtNoCita;
    public static javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
