/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.HistorialClinicoDAOImpl;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import modelo.HistorialClinico;
import sistemaconsultorionutri.Dashboard;
import static sistemaconsultorionutri.Dashboard.showView;

/**
 *
 * @author Yair
 */
public class SubirHistorialClinico extends javax.swing.JPanel {

    private File wordFile;

    /**
     * Creates new form Citas
     */
    public SubirHistorialClinico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSeleccionarArchivo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIdPacienteHC = new javax.swing.JTextField();
        btnCargarArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPacienteNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(788, 496));
        setPreferredSize(new java.awt.Dimension(988, 588));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(788, 496));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("ID paciente");

        btnSeleccionarArchivo.setBackground(new java.awt.Color(0, 102, 102));
        btnSeleccionarArchivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSeleccionarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarArchivo.setText("Seleccionar archivo...");
        btnSeleccionarArchivo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 15, new java.awt.Color(0, 0, 0)));
        btnSeleccionarArchivo.setBorderPainted(false);
        btnSeleccionarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarArchivo.setFocusPainted(false);
        btnSeleccionarArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSeleccionarArchivo.setIconTextGap(10);
        btnSeleccionarArchivo.setSelected(true);
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 15, new java.awt.Color(0, 0, 0)));
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setIconTextGap(10);
        btnCancelar.setSelected(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtIdPacienteHC.setEditable(false);
        txtIdPacienteHC.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPacienteHC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtIdPacienteHC.setForeground(new java.awt.Color(102, 102, 102));
        txtIdPacienteHC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtIdPacienteHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPacienteHCActionPerformed(evt);
            }
        });

        btnCargarArchivo.setBackground(new java.awt.Color(0, 102, 102));
        btnCargarArchivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarArchivo.setText("Cargar");
        btnCargarArchivo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 15, new java.awt.Color(0, 0, 0)));
        btnCargarArchivo.setBorderPainted(false);
        btnCargarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargarArchivo.setFocusPainted(false);
        btnCargarArchivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCargarArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCargarArchivo.setIconTextGap(10);
        btnCargarArchivo.setSelected(true);
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        txtPacienteNombre.setEditable(false);
        txtPacienteNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtPacienteNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPacienteNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtPacienteNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPacienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCargarArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(txtPacienteNombre)
                    .addComponent(txtIdPacienteHC)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtIdPacienteHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtPacienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cargar Historial Clínico");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/dieta-planeacion.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Agregar un filtro para archivos de Word (DOCX)
        FileNameExtensionFilter wordFilter = new FileNameExtensionFilter("Archivos de Word", "docx");
        fileChooser.setFileFilter(wordFilter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // Verificar que el archivo seleccionado sea un archivo de Word (DOCX)
            if (selectedFile.getName().toLowerCase().endsWith(".docx")) {
                wordFile = selectedFile;

                // Cambiar el texto del botón para mostrar el nombre del archivo seleccionado
                btnSeleccionarArchivo.setText(selectedFile.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Selecciona un archivo de Word válido (DOCX).");
            }
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vistas.Pacientes pacientes = new Pacientes();
        showView(pacientes);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        String idPaciente = txtIdPacienteHC.getText();
        String nombrePaciente = txtPacienteNombre.getText();

        if (wordFile != null && idPaciente != null && !idPaciente.isEmpty() && nombrePaciente != null && !nombrePaciente.isEmpty()) {
            try {
                FileSystemView fileSystemView = FileSystemView.getFileSystemView();
                File documentsFolder = fileSystemView.getDefaultDirectory();
                File historialesClinicosFolder = new File(documentsFolder, "historialesclinicos");

                if (!historialesClinicosFolder.exists()) {
                    historialesClinicosFolder.mkdir();
                }

                String nuevoNombreArchivo = "H C " + nombrePaciente + idPaciente + ".docx";  // Nuevo formato de nombre
                File destino = new File(historialesClinicosFolder, nuevoNombreArchivo);
                Files.copy(wordFile.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                HistorialClinico historialClinico = new HistorialClinico();
                historialClinico.setPacienteId(Integer.parseInt(idPaciente));
                historialClinico.setArchivoNombre(nuevoNombreArchivo);
                historialClinico.setArchivoReferencia(destino.getAbsolutePath());

                HistorialClinicoDAOImpl historialClinicoDAO = new HistorialClinicoDAOImpl();
                historialClinicoDAO.agregar(historialClinico);

                Dashboard.mostrarMensajeAviso("¡Historial clínico subido de forma exitosa!");
                vistas.Pacientes pacientes = new Pacientes();
                showView(pacientes);

            } catch (Exception e) {
                e.printStackTrace();
                Dashboard.mostrarMensajeError("Ha ocurrido un error");
            }
        } else {
            Dashboard.mostrarMensajeAlerta("Debe completar toda la información solicitada");
        }
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void txtIdPacienteHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPacienteHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPacienteHCActionPerformed

    private void txtPacienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTextField txtIdPacienteHC;
    public static javax.swing.JTextField txtPacienteNombre;
    // End of variables declaration//GEN-END:variables
}
